# packages-dhi — DHI-native image pipeline for wellmaintained packages
# Prerequisites: Docker (with buildx), Just, yq
# Build & release pipeline: build.yml (PR) → pre-release.yml (PR closed/merged) → deploy-release-website.yml (release published)

set dotenv-load := false

repo_root := justfile_directory()
app := env("APP", "sbomify-current")
app_manifest := repo_root / "apps" / app / "app-images.yaml"
app_lock := repo_root / "apps" / app / "app-images.lock.yaml"
app_compose := repo_root / "apps" / app / "deployments" / "docker-compose.yml"
app_release_website := repo_root / "apps" / app / "release-website"
artifacts_dir := repo_root / "artifacts"

mod ci

# ── Helpers ────────────────────────────────────────

# Resolve the registry for a custom image name
_image-registry image:
    @yq -r '."{{image}}".registry | select(. != null)' {{app_manifest}}

# ── Stock DHI Images ──────────────────────────────

# Extract attestations for all stock DHI images
extract-dhi-attestations:
    APP={{app}} {{repo_root}}/scripts/extract-dhi-attestations

# ── Release ────────────────────────────────────────

# Generate Hugo data files from build artifacts
release-data:
    APP={{app}} {{repo_root}}/scripts/extract-release-data

# Build the release website locally
release-website:
    APP={{app}} just release-data
    {{repo_root}}/bin/hugo --source {{app_release_website}} --minify

# Serve the release website locally for preview
release-website-serve:
    APP={{app}} just release-data
    {{repo_root}}/bin/hugo server --source {{app_release_website}} --bind 0.0.0.0 --port 1313

# Assemble compliance pack ZIP
compliance-pack version:
    APP={{app}} {{repo_root}}/scripts/build-compliance-pack {{version}}

# ── Compose ───────────────────────────────────────

# Build digest-pinned docker-compose.yml from source + app-images.lock.yaml
build-app-compose:
    #!/usr/bin/env bash
    set -euo pipefail
    src="{{app_compose}}"
    out="{{artifacts_dir}}/docker-compose.yml"
    mkdir -p "{{artifacts_dir}}"
    cp "$src" "$out"
    for name in $(yq -r 'to_entries[] | select(.value.source != null and .value.digest != null) | .key' "{{app_lock}}"); do
        source=$(yq -r ".$name.source" "{{app_lock}}")
        digest=$(yq -r ".$name.digest" "{{app_lock}}")
        pinned="${source}@${digest}"
        echo "  ${name}: ${source} → ${pinned}"
        sed -i "s|image: ${source}|image: ${pinned}|g" "$out"
    done
    echo "Written to ${out}"

# ── App Deployment ────────────────────────────────

# Bring up the local app stack via docker compose
app-up:
    docker compose -f {{app_compose}} up -d

# Stop the app stack and remove containers + volumes
app-down:
    docker compose -f {{app_compose}} down -v

# Tail logs from all app services
app-logs:
    docker compose -f {{app_compose}} logs -f

# ── Update ────────────────────────────────────────

# Update everything: tool checksums, stock image digests, then lint
update: update-tools update-app-images lint-yaml
    @echo ""
    @echo "=== Summary ==="
    @just images

# Resolve tool URLs from version templates and compute checksums
update-tools:
    #!/usr/bin/env bash
    set -euo pipefail
    spec="{{repo_root}}/common/tool-versions.yaml"
    lock="{{repo_root}}/common/tool-versions.lock.yaml"

    echo "=== Pinning tool checksums ==="
    # Save existing lock for preserving uvx versions (which live only in the lock file)
    old_lock=$(mktemp)
    [ -f "$lock" ] && cp "$lock" "$old_lock" || touch "$old_lock"
    echo "# AUTO-GENERATED by 'just update-tools' — do not edit" > "$lock"

    for name in $(yq -r 'keys | .[]' "$spec"); do
        # Handle uvx-type tools (version lives in lock file, not spec)
        tool_type=$(yq -r ".$name.type // \"binary\"" "$spec")
        if [ "$tool_type" = "uvx" ]; then
            version=$(yq -r ".$name.version" "$old_lock")
            [[ "$version" == "null" || -z "$version" ]] && { echo "  $name: ERROR — no version in lock file" >&2; continue; }
            yq -i ".$name.version = \"$version\"" "$lock"
            yq -i ".$name.type = \"uvx\"" "$lock"
            echo "  $name v$version (uvx)"
            continue
        fi

        version=$(yq -r ".$name.version" "$spec")

        url_template=$(yq -r ".$name.url" "$spec")
        binary=$(yq -r ".$name.binary" "$spec")
        raw=$(yq -r ".$name.raw // false" "$spec")

        # Resolve ${version} in URL template
        url="${url_template//\$\{version\}/$version}"

        echo -n "  $name v$version: "
        tmpfile=$(mktemp)
        curl -sL "$url" -o "$tmpfile"
        checksum=$(sha256sum "$tmpfile" | cut -d' ' -f1)
        rm -f "$tmpfile"
        echo "sha256:${checksum}"

        yq -i ".$name.version = \"$version\"" "$lock"
        yq -i ".$name.url = \"$url\"" "$lock"
        yq -i ".$name.checksum = \"sha256:$checksum\"" "$lock"
        yq -i ".$name.binary = \"$binary\"" "$lock"
        if [ "$raw" = "true" ]; then
            yq -i ".$name.raw = true" "$lock"
        fi
    done

# Pin stock image digests and generate app lock file
update-app-images:
    #!/usr/bin/env bash
    set -euo pipefail
    manifest="{{app_manifest}}"
    lock="{{app_lock}}"

    echo "=== Pinning app image digests ==="
    cp "$manifest" "$lock"
    sed -i '1i # AUTO-GENERATED by '\''just update-app-images'\'' — do not edit' "$lock"
    for name in $(yq -r 'to_entries[] | select(.value | has("source")) | .key' "$manifest"); do
        source=$(yq -r ".$name.source" "$manifest")
        echo -n "  $name ($source): "
        digest=$("{{repo_root}}/bin/crane" digest "$source" 2>/dev/null) || true
        if [ -n "$digest" ]; then
            echo "$digest"
            yq -i ".$name.digest = \"$digest\"" "$lock"
        else
            echo "(failed to resolve digest)"
        fi
    done

# ── Lint ──────────────────────────────────────────

# Lint all YAML files in the repo
lint-yaml:
    #!/usr/bin/env bash
    set -euo pipefail
    echo "=== Linting YAML ==="
    find "{{repo_root}}" \
        -name '*.yaml' -o -name '*.yml' \
        | grep -v -e 'artifacts/' -e '\.tmp/' \
                  -e 'release-website/public/' -e 'release-website/static/artifacts/' \
        | sort \
        | xargs "{{repo_root}}/bin/yamllint" -c "{{repo_root}}/.yamllint.yaml"
    echo "  all files passed"

# ── Info ───────────────────────────────────────────

# Show all images and their sources
images:
    @echo "=== Tools ==="
    @yq -r 'to_entries[] | "  \(.key): \(.value.version)"' {{repo_root}}/common/tool-versions.yaml
    @echo ""
    @echo "=== Stock Images ==="
    @yq -r 'to_entries[] | select(.value | has("source")) | "  \(.key): \(.value.source)"' {{app_manifest}}
    @echo ""
    @echo "=== Custom Images ==="
    @yq -r 'to_entries[] | select(.value | has("definition")) | "  \(.key): \(.value.definition) → \(.value.registry)"' {{app_manifest}}
