name: Build senaite-current

on:
  pull_request:
    paths:
      - 'apps/senaite-current/**'
      - 'common/**'
      - 'scripts/**'
      - 'Justfile'
      - 'ci/**'
      - 'bin/**'
      - '.github/workflows/_app-build.yml'
      - '.github/workflows/build-senaite-current.yml'
      - '.github/actions/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/_app-build.yml
    with:
      app: senaite-current
    secrets: inherit
